### ISSUE TITLE
Editor gets locked in certain cases on Android

### ISSUE THREAD

**Issue by FRBFStudios** [Alphalaneous/Relocate-Build-Tools#1]
I am on a phone with Android x64 on it, and each time I do something on the "edit group" screen or edit a text object (and maybe some other actions that I didn't find yet) the editor becomes largely unresponsive. I can't swipe to move anymore, the only buttons I can use are the editor tab buttons, and the only way to fix it is to press the "back" button next to the digital home button to pull up the editor pause menu, exit the level, and then re-enter it.
Finding the source of this bug was very complicated, but if I troubleshot it right, this should be the faulty mod. If it truly is, please try fixing this quickly because it makes creating genuinely insufferable.
Thank you in advance!

**Comment by Alphalaneous** [comment]
Just to check, are you on the latest version of the mod? Does this happen with BetterEdit disabled?

**Comment by FRBFStudios** [comment]
Yes, to both of these questions. I update all of my mods daily and disabling BE was the first thing I tried after encountering this bug for the first time, it didn't work.

**Comment by Alphalaneous** [comment]
Very strange, I will look into it

**Comment by Alphalaneous** [comment]
Try it now, just updated it, should hopefully be fixed

**Comment by FRBFStudios** [comment]
It seems to be fixed now. TYSM!!!
