### ISSUE TITLE
absolute scaling doesn't work

### ISSUE THREAD

**Issue by xHugoLA** [Alphalaneous/Relocate-Build-Tools#2]
Absolute scaling doesn't work when the mod is activated, I also disabled betteredit or any mod if there was a conflict, but it still didn't work anyway, please if you can fix this in a future update, I'd be grateful.

![image](https://github.com/user-attachments/assets/5cf9801c-af16-4792-a016-cf531efa9599)

**Comment by Alphalaneous** [comment]
Should be resolved in this next update
